---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx"
  namespace: "development"
  labels:
    app: "nginx"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx"
  template:
    metadata:
      labels:
        app: "nginx"
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: gcs-fuse-sa
      containers:
      - name: "nginx"
        image: "nginx"
        volumeMounts:
        - name: gcsfuse-test
          mountPath: /data
          readOnly: false
      volumes:
      - name: gcsfuse-test
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: YOUR_BUCKET_NAME
            mountOptions: "implicit-dirs"
