apiVersion: v1
kind: Pod
metadata:
  name: gcsfuse-test
  namespace: default
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - image: ubuntu
    name: ubuntu
    command: [ "sleep" ]
    args: [ "infinity" ]
    volumeMounts:
    - name: gcsfuse-test
      mountPath: /data
      readOnly: false
  serviceAccountName: gcs-fuse-sa
  volumes:
  - name: gcsfuse-test
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: gc-storage-poc-09022025-73576e33
        mountOptions: "implicit-dirs"
